#!/bin/bash

# Copyright 2015 Google Inc. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Default SDK local dir name
SDK_DIR=$HOME/google-cloud-sdk
# Download URL of the Google Cloud SDK
SDK_URL=https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz

function install_or_update_gcloud {
  set -e  # fail on errors

  # don't ask any questions
  export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  export CLOUDSDK_PYTHON_SITEPACKAGES=1

  if $(command -v gcloud >/dev/null 2>&1); then
    GCLOUD_BIN=gcloud
  else
    GCLOUD_BIN=$SDK_DIR/bin/gcloud
  fi

  if ! $($GCLOUD_BIN --version >/dev/null 2>&1); then
    mkdir -p $SDK_DIR
    curl -o /tmp/gcloud.tar.gz $SDK_URL
    tar xzf /tmp/gcloud.tar.gz --strip 1 -C $SDK_DIR
    rm /tmp/gcloud.tar.gz
    $SDK_DIR/install.sh
    GCLOUD_BIN=$SDK_DIR/bin/gcloud
  fi

  # TODO: uncomment when this damn thing stops breaking!
  #$GCLOUD_BIN components update app -q
}

