#!/bin/bash

# Copyright 2015 Google Inc. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

if [ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]; then
  exit 0;
fi

gulp jshint &> /dev/null
if [ "$?" != "0" ]; then
  echo "Found some JS errors. Check with 'gulp jshint' before committing."
  exit 1;
fi

gulp jscs &> /dev/null
if [ "$?" != "0" ]; then
  echo "Unstyled JS. Check with 'gulp jscs' before committing."
  exit 1;
fi

