#!/bin/bash

if [ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]; then
  exit 0;
fi

gulp jshint &> /dev/null
if [ "$?" != "0" ]; then
  echo "Found some JS errors. Check with 'gulp jshint' before committing."
  exit 1;
fi

gulp jscs &> /dev/null
if [ "$?" != "0" ]; then
  echo "Unstyled JS. Check with 'gulp jscs' before committing."
  exit 1;
fi

